[package]
name = "fluxcore"
version = "0.1.0"
authors = ["Jonathan Daugherty <cygnus@foobox.com>"]

[dependencies]
nalgebra = "0.16.5"
rand = "0.5.5"
samplers = { path = "../samplers" }
crossbeam = "0.5.0"
rayon = "1.0.3"
num = "0.2.0"
