[package]
name = "flux-node"
version = "0.1.0"
authors = ["Jonathan Daugherty <cygnus@foobox.com>"]
edition = "2018"

[dependencies]
fluxcore = { path = "../fluxcore" }
serde_cbor = "0.9"
crossbeam = "0.5.0"
